<div id="ajaxcart-load-ajax" style="display:none;">
	<div id="load" class="ajaxcart-overlay">&nbsp;</div>
	<div id="ajaxcart-loading" class="ajaxcart-loading">
		<img alt="<?php echo $this->__('Loading') ?>..." src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" /><br />
		<?php echo $this->__('Loading') ?>...
	</div>
	<div id="form-paypal" style="display:none;" class="form-paypal">
	</div>
</div>
<p id="scroll" style="height:0px; position:fixed; top:100px;"></p>



<ol class="one-step-checkout clearfix">
	<li>
		<h1 class="checkout_header"><?php echo $this->getCheckoutTitle();?></h1>
		<p style="font-size:18px;"><?php echo $this->configData['checkout_description'] ? $this->configData['checkout_description'] : 'Please fill in the fields below and click Place order to complete your purchase!';?></p>
	</li>
	<?php if ($this->isShowLoginLink() && !$this->isCustomerLoggedIn()):?>
	<li class="onestepcheckout-login-link">
		<!--<a href="#" id="show-login" onclick ="showloginbox();return false;">-->
		<a href="javascript:void(0);"  id="onestepcheckout-login-link">
		<?php echo $this->configData['login_link_title'] ? $this->configData['login_link_title'] : $this->__('Already have an account?Click here to login')?>
		</a>
	</li>
	<?php endif?>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<li class="address-order">
		<form id="one-step-checkout-form" method="post" action="<?php echo $this->getCheckoutUrl(); ?>">
			<div class="address-information">
				<?php echo $this->getChildHtml('onestepcheckout.billing');?>				
				<?php echo $this->getChildHtml('onestepcheckout.shipping');?>
			</div>
			<div class="order-information">
				<ol>
					<?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()):?>
					<li class="shipping-method">						
						<h3  id="shipping_method_step_header" class="step_2">
							<?php echo $this->__('SHIPPING METHOD'); ?>
						</h3>
						<div class="onestepcheckout-shipping-method-section">
							<?php echo $this->getChildHtml('onestepcheckout.shipping_method'); ?>						
						</div>
						<div class="ajax-loader1" id="ajax-loader1" style="display:none;"></div>
					</li>
					<?php elseif (Mage::helper('onestepcheckout')->isHideShippingMethod()):?>
						<?php $_shippingMethod = $this->hasOnlyOneShippingMethod();?>
						<span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_shippingMethod;?>" id="s_method_<?php echo $_shippingMethod; ?>" checked="checked" /></span>
					<?php endif;?>
					<li class="payment-method">						
						<h3 id="payment_method_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()):?> class="step_3"<?php else:?> class="step_2"<?php endif;?>>
							<?php echo $this->__('PAYMENT METHOD'); ?>
						</h3>						
						<?php echo $this->getChildHtml('onestepcheckout.payment_method'); ?>												
					</li>
					<li class="order-review-info">						
						<h3 id="review_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()):?> class="step_4" <?php else:?> class="step_3"<?php endif?>>
							<?php echo $this->__('ORDER REVIEW'); ?>
						</h3>					
						<?php echo $this->getChildHtml('onestepcheckout.review') ?>						
						<div class="ajax-loader3" id="ajax-loader3"  style="display:none;"></div>
					</li>
				</ol>
			</div>
			<?php $_helper = Mage::helper('onestepcheckout');?>
			<?php if(!$_helper->isCustomerLoggedIn() && $_helper->showLoginLink()): ?>
				<?php echo $this->getChildHtml('login-popup'); ?>
			<?php endif; ?>			
		</form>
	</li>
</ol>

<script type="text/javascript">
//<![CDATA[	
	var preloadImage = '<?php echo $this->getSkinUrl('images/onestepcheckout/preload.gif')?>';
	var shipping_method_url = '<?php echo $this->getUrl('onestepcheckout/index/save_shipping', array('_secure' => true));?>';
	var enable_update_payment = <?php echo $this->configData['update_payment'] ? 'true' : 'false'; ?>;
    var login_url = '<?php echo $this->getUrl('onestepcheckout/index/show_login', array('_secure' => true));?>';	
	var show_login_link = <?php echo $this->configData['show_login_link'] ? 'true' : 'false'; ?>;
	var show_term_condition_url = '<?php echo $this->getUrl('onestepcheckout/index/show_term_condition', array('_secure' => true));?>';
	var form = $('one-step-checkout-form');
	var reload_payment = <?php echo $this->configData['reload_payment']; ?>
	
	function showloginbox() {
		var url = '<?php echo $this->getUrl('onestepcheckout/index/show_login', array('_secure' => true));?>';
		showLogin(url);
	}

	function showforgotpwd() {
		var url = '<?php echo $this->getUrl('onestepcheckout/index/show_password', array('_secure' => true));?>';
		showpwdbox(url);
	}
	
	function showPasswordForm() {
		$('onestepcheckout-login').hide();
		$('onestepcheckout-forgot-password').show();
	}
	
	function showloginform() {
		$('onestepcheckout-forgot-password').hide();
		$('onestepcheckout-login').show();		
	}
	
	function submitLoginForm() {
		var login_validator = new Validation('onestepcheckout-login-form');
		if (login_validator.validate()) {
			showLoginLoading();
			var url = '<?php echo $this->getUrl('onestepcheckout/index/loginPost', array('_secure' => true))?>';
			var email = $('osclogin:email_address').value;
			var password = $('osclogin:password').value;
			var parameters = {email:email, password:password};			
			var loginRequest = new Ajax.Request(url, {
				parameters: parameters,
				onComplete: loginProcess.bindAsEventListener(this),
				onFailure: ""
			});						
		}
	}
	
	function retrievePassword() {
		var passwordValidator = new Validation('osc-forgotpassword-form');
		if (passwordValidator.validate()) {
			showPassLoading();
			var url = '<?php echo $this->getUrl('onestepcheckout/index/retrievePassword', array('_secure' => true))?>';
			var email = $('forgotpassword_email_address').value;
			var parameters = {email:email};			
			var loginRequest = new Ajax.Request(url, {
				parameters: parameters,
				onComplete: passwordProcess.bindAsEventListener(this),
				onFailure: ""
			});
		}
	}
		
	
	<?php if ($this->configData['enable_ajax']):?>
		var save_address_url = '<?php echo $this->getUrl('onestepcheckout/index/save_address', array('_secure' => true))?>';
		
		<?php if ($this->isAjaxBillingField('country')):?>
			//save billing when country is changed
			Event.observe('billing:country_id', 'change', function() {
				//check empty fields
				var empty = checkEmptyFields($('billing-new-address-form'));
				if(empty == false || reload_payment==2)
					save_address_information(save_address_url);
			});
			<?php if ($this->isShowShippingAddress()):?>
			Event.observe('shipping:country_id', 'change', function() {
				//check empty fields
				var empty = checkEmptyFields($('shipping-new-address-form'));
				if(empty == false || reload_payment==2)
					save_address_information(save_address_url);
			});
			<?php endif;?>
		<?php endif;?>
		
		<?php if ($this->isAjaxBillingField('state/region')):?>
			//save billing when state / region is changed
				Event.observe('billing:region_id', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				Event.observe('billing:region', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php if ($this->isShowShippingAddress()):?>
				Event.observe('shipping:region_id', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				Event.observe('shipping:region', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php endif;?>
		<?php endif;?>
		
		<?php if ($this->isAjaxBillingField('postcode')):?>
			//save billing when postcode is changed
				Event.observe('billing:postcode', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php if ($this->isShowShippingAddress()):?>
				Event.observe('shipping:postcode', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php endif;?>
		<?php endif;?>
		
		<?php if ($this->isAjaxBillingField('city')):?>
			//save billing when city is changed
				Event.observe('billing:city', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php if ($this->isShowShippingAddress()):?>
				Event.observe('shipping:city', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});			
				<?php endif;?>
		<?php endif;?>
		
		//telephone
		Event.observe('billing:telephone', 'change', function() {
			//check empty fields
			var empty = checkEmptyFields($('billing-new-address-form'));
			if(empty == false)
				save_address_information(save_address_url);
		});
		Event.observe('shipping:telephone', 'change', function() {
			//check empty fields
			var empty = checkEmptyFields($('shipping-new-address-form'));
			if(empty == false)
				save_address_information(save_address_url);
		});
	<?php endif?>			
	
	//document.observe('dom:loaded', function() {
	//fix for IE9
	Event.observe(window, 'load', function() {
		if($RF(form, 'payment[method]') != null)	{		
			var payment_method = $RF(form, 'payment[method]');
			if ($('container_payment_method_' + payment_method)) {
				$('container_payment_method_' + payment_method).show();
			}
			if ($('payment_form_' + payment_method)) {
				$('payment_form_' + payment_method).show();		
			}
		}
	});
	
	function disable_payment(){
		var options = document.getElementsByName('payment[method]');
		for(var i=0;i<options.length;i++){
			if(!$(options[i].id).checked){
				var container = options[i].id.replace('p_method','container_payment_method');
				if($(container)){
					$(container).innerHTML = '';
				}
			}
		}	
	}

	function checkpayment(){
	var options = document.getElementsByName('payment[method]');
		var pay = true;
		for(var i=0;i<options.length;i++){
			if($(options[i].id).checked){
				pay = false;
				break;
			}
		}
		if(pay==true){
			return false;
		}
		return true;
	}

	function oscPlaceOrder(element){
		var validator  = new Validation('one-step-checkout-form');
		if (validator.validate()) {
			if($('p_method_hosted_pro') && $('p_method_hosted_pro').checked){
				$('onestepcheckout-place-order-loading').show();
				$('onestepcheckout-button-place-order').removeClassName('btn-checkout');
				$('onestepcheckout-button-place-order').addClassName('place-order-loader');
				$('ajaxcart-load-ajax').show();
				checkAjax('<?php echo $this->getUrl('onestepcheckout/index/saveOrderPro', array('_secure' => true));; ?>');
			}else{
				if(checkpayment()) {
					element.disabled = true;
					already_placing_order = true;
					disable_payment();
					$('onestepcheckout-place-order-loading').show();
					$('onestepcheckout-button-place-order').removeClassName('btn-checkout');
					$('onestepcheckout-button-place-order').addClassName('place-order-loader');
					$('one-step-checkout-form').submit();
					// checkAjax('<?php echo $this->getCheckoutUrl(); ?>');
				}
			}
		}
	}
	
	function checkAjax(url){	
		var form = $('one-step-checkout-form');		
		var payment_method = $RF(form, 'payment[method]');
		var shipping_method = $RF(form, 'shipping_method');		
		var parameters = {
            payment : payment_method,
			shipping_method : shipping_method			
		}
		get_billing_data(parameters);	
		get_shipping_data(parameters);
		
		if($('giftmessage-type') && $('giftmessage-type').value != ''){
			parameters[$('giftmessage-type').name] = $('giftmessage-type').value;
		}
		if($('create_account_checkbox_id') && $('create_account_checkbox_id').checked){
			parameters['create_account_checkbox'] = 1;
		}	
		if($('gift-message-whole-from') && $('gift-message-whole-from').value != ''){
			parameters[$('gift-message-whole-from').name] = $('gift-message-whole-from').value;
		}
		if($('gift-message-whole-to') && $('gift-message-whole-to').value != ''){
			parameters[$('gift-message-whole-to').name] = $('gift-message-whole-to').value;
		}
		if($('gift-message-whole-message') && $('gift-message-whole-message').value != ''){
			parameters[$('gift-message-whole-message').name] = $('gift-message-whole-message').value;
		}
		if($('billing-address-select') && $('billing-address-select').value != ''){
			parameters[$('billing-address-select').name] = $('billing-address-select').value;
		}
		if($('shipping-address-select') && $('shipping-address-select').value != ''){
			parameters[$('shipping-address-select').name] = $('shipping-address-select').value;
		}

		new Ajax.Request(url,{
			method: 'post',
			evalJS: 'force',
			onSuccess: function(transport){
				// alert(JSON.parse(transport.responseText).url);
				if(JSON.parse(transport.responseText).url=='null' || JSON.parse(transport.responseText).url==null){
					$('ajaxcart-loading').style.display='block';
					$('ajaxcart-loading').style.top='15%';
					$('ajaxcart-loading').style.left='40%';
					$('ajaxcart-loading').style.width='551px';
					$('ajaxcart-loading').style.height='400px';
					$('ajaxcart-loading').style.overflow='hidden';
					$('ajaxcart-loading').style.padding='5px';		
					$('ajaxcart-loading').innerHTML=JSON.parse(transport.responseText).html;
					$('iframe-warning').style.textAlign='left';					
				}
				else
				{					
					window.location.href= JSON.parse(transport.responseText).url;
				}
			},
			onFailure: function(transport){  
			},
			parameters: parameters
		});
	}	
	
	<?php //if ($this->isCustomerLoggedIn()):?>
	var save_address_url = '<?php echo $this->getUrl('onestepcheckout/index/save_address', array('_secure' => true))?>';
	save_address_information(save_address_url);
	<?php //endif;?>
	
//]]>
</script>

<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>
<div id="loading-process" style="display: none;"></div>

<!-- Terms and conditions -->
<?php $_helper = Mage::helper('onestepcheckout');?>
<?php $width = $_helper->getTermPopupWidth() ? $_helper->getTermPopupWidth() : 482;?>
<?php $height = $_helper->getTermPopupHeight() ? $_helper->getTermPopupHeight() : 530;?>
<?php if($_helper->enableTermsAndConditions()): ?>
	<?php if(!$_helper->enableCustomSize()): ?>
	<div id="onestepcheckout-toc-popup" style="display:none;">
		<div class="onestepcheckout-popup-wrapper" style="height: 515px !important;">
			<div class="onestepcheckout-popup-wrapper-inner">
				<h1><?php echo $_helper->getTermTitle(); ?></h1>

				<div class="onestepcheckout-toc-terms">
					<?php echo $_helper->getTermsConditionsHtml(); ?>
				</div>

				<p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
			</div>
		</div>
		<div class="onestepcheckout-popup-footer">&nbsp;</div>
	</div>
	<?php else:?>
		<div id="onestepcheckout-toc-popup" style="display:none; width:<?php echo $width?>px; height:<?php echo $height?>px;">
		<div class="onestepcheckout-popup-wrapper2" style="width:<?php echo $width?>px; height:<?php echo $height?>px;">
			<div class="onestepcheckout-popup-wrapper-inner2">
				<h1><?php echo $_helper->getTermTitle(); ?></h1>

				<div class="onestepcheckout-toc-terms">
					<?php echo $_helper->getTermsConditionsHtml(); ?>
				</div>

				<p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
			</div>
		</div>
		<div class="onestepcheckout-popup-footer2">&nbsp;</div>
	</div>
	<?php endif; ?>
<script>
Event.observe(window, 'load', function() {

    var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
        overlayOpacity: 0.65,
        fade: true,
        fadeDuration: 0.3
    });

    $('onestepcheckout-toc-link').observe('click', function(e) {
        e.preventDefault();
        termsPopup.open();
		
		var h = window.document.documentElement.clientHeight;
		if(h<=530){
			$('scroll').scrollTo();
		}
    });

    $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e) {
        e.preventDefault();
        termsPopup.close();
    });

});

</script>
<?php endif; ?>
<?php if ($this->isShowLoginLink() && !$this->isCustomerLoggedIn()):?>
<script>
	$('onestepcheckout-login-link').observe('click', function(e) {
			var h = window.document.documentElement.clientHeight;
			var popupLogin = $('onestepcheckout-login-popup').getHeight();
			//alert(h);
			//alert(popupLogin);
			
				$('scrollLogin').scrollTo();
		

    });
</script>
<?php endif;?>